Day-13 of #100DaysOfCode

## **Numpy**

NumPy stands for ‘Numerical Python’ or ‘Numeric Python’. It is an open source module of Python which provides fast mathematical computation on arrays and matrices. Since, arrays and matrices are an essential part of the Machine Learning ecosystem, NumPy along with Machine Learning modules like Scikit-learn, Pandas, Matplotlib, TensorFlow, etc. complete the Python Machine Learning Ecosystem.

NumPy provides the essential multi-dimensional array-oriented computing functionalities designed for high-level mathematical functions and scientific computation. Numpy can be imported into the notebook using

In [3]:
import numpy as np

NumPy’s main object is the homogeneous multidimensional array. It is a table with same type elements, i.e, integers or string or characters (homogeneous), usually integers. In NumPy, dimensions are called axes. The number of axes is called the rank.

There are several ways to create an array in NumPy like np.array, np.zeros, no.ones, etc. Each of them provides some flexibility.

In [ ]:
np_height = np.array([1.84, 1.79,
1.82, 1.9, 1.8])
np_weight = np.array([66.5, 60.3,
64.7, 89.5, 69.8])

bmi = np_weight / np_height ** 2
bmi

array([19.64201323, 18.81963734, 19.53266514, 24.79224377, 21.54320988])



---



---



Day-14 of #100DaysOfCode

# Creating NumPy Arrays
We can create an Array using NumPy by wrapping it first in a List and converting it to a numpy array.

In [ ]:
mylist = [1,2,3,4,5]
myarr = np.array([mylist])
myarr

array([[1, 2, 3, 4, 5]])

or directly without creating a variable list first

In [ ]:
myarr = np.array([1,2,3,4,5])
myarr

array([1, 2, 3, 4, 5])

There are a few more functions that can be used to create arrays, including zeros(), ones(), arange(), linspace(), logspace().

- zeros() -> Create array with value 0

- ones() -> Create array with value 1

- range() -> Create array with values in range

- linspace() -> Create array with values in interval

- logspace() -> Creates array with Base10 log values in interval

In [ ]:
np.zeros(5) # creates an array of 0,  5 times

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5) # create array with value 1,  5 times

array([1., 1., 1., 1., 1.])

In [ ]:
np.arange(1, 10, 2) #arange(start, stop, step)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1, 10, 2) # linespace(start, stop, number)

array([ 1., 10.])

In [ ]:
np.logspace(1, 10, 2) # logspace(start, stop, number)

array([1.e+01, 1.e+10])

## Multidimensional Array
One of the interesting features of NumPy is that it can create multidimensional arrays and manipulate arrays easily and quickly

Multidimensional array is an array that has more than 1 dimension (1D), can be 2D, 3D, 4D and so on

The method of creating a multidimensional array is the same as making a 1-dimensional array, the difference is only in the parameters used

Here's an example of making a 2-dimensional array

In [ ]:
arrku = np.array([[1,2,3,4,5], [2,4,6,8,10]])

The array above is in the form of (2,5) meaning it has 2 rows and 5 columns

We can see the number of elements in each dimension by using  ***shapes***

In [ ]:
arrku.shape

(2, 5)

## Indexing and Slicing
We can also do indexing and slicing of arrays easily

Indexing starts at 0 and starts with bracket notation “[ ]”

For example, we want to find the values that are at index 0, 2, and 4

In [ ]:
arr_A = np.array([1,2,3,4,5])
print(arr_A[0])
print(arr_A[2])
print(arr_A[4])

1
3
5


In [ ]:
#To retrieve a row value add “:”
arr_A = np.array([1,2,3,4,5])
print(arr_A[0:4])

[1 2 3 4]


In [ ]:
#We can also do slicing on multidimensional arrays
arr_A = np.array([[1,2,3,4,5], [2,4,6,8,10]])
print(arr_A)
print(arr_A[1,1])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
4


## Arithmetic Operation
We can use arithmetic operations such as addition, subtraction, multiplication, division and power

The operators used are +, -, *, / and **

The following is an example of arithmetic operations on arrays

In [ ]:
arr_A = np.array([1,2,3,4,5])
arr_B = np.array([2,2,2,2,2])

print("Addition = ", arr_A + arr_B)
print("Subtraction = ", arr_A - arr_B)
print("Multiplication = ", arr_A * arr_B)
print("Division = ", arr_A / arr_B)
print("Power = ", arr_A ** arr_B)

Addition =  [3 4 5 6 7]
Subtraction =  [-1  0  1  2  3]
Multiplication =  [ 2  4  6  8 10]
Division =  [0.5 1.  1.5 2.  2.5]
Power =  [ 1  4  9 16 25]


## Mathematical Operation
NumPy has mathematical functions that can be used on Arrays

Some examples of statistical functions include min(), max(), mean(), sum(), std()

In [ ]:
myarr = np.array([1,2,3,4,5])
print("Minimum  = ", myarr.min())
print("Maximum  = ", myarr.max())
print("Average = ", myarr.mean())
print("Total value = ", myarr.sum())
print("Standard Deviation = ", myarr.std())

Minimum  =  1
Maximum  =  5
Average =  3.0
Total value =  15
Standard Deviation =  1.4142135623730951


In [ ]:
#There are also functions argmin() and argmax() to get the index of the minimum and maximum values
print("Min Index = ", myarr.argmin())
print("Max index = ", myarr.argmax())

Min Index =  0
Max index =  4




---



---



Day-15 of #100DaysOfCode

# **Pandas**
Pandas is a Python library that is built on top of NumPy and is suitable for preprocessing data and analysis

Panda is capable of processing various types of data such as CSV, JSON, Excel, TXT, HTML, XML, PDF, Pickle and others

In [2]:
#To use Pandas we have to import it first
import pandas as pd

# Pandas Series
Pandas Series is a basic Pandas data structure in the form of a one-dimensional labeled array. Series can accommodate various types of data such as integers, strings, floats, etc.

Series can be described as an extension of NumPy 1D which has an explicit index

More clearly the difference between Pandas Series vs NumPy Array can be read here

Create Pandas Series
We can create Series with input from List and Array

In [ ]:
# List
myseries = pd.Series([2,4,6,8,10])
# Array
myseries = pd.Series(np.array([2,4,6,8,10]))



---



---



Day-16 of #100DaysOfCode

in pandas We can also modify the index shape like this

In [ ]:
data = np.array([2,4,6,8,10])
nilai_series = pd.Series(data, index=['a','b','c','d','e'])

nilai_series

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [ ]:
#To access the value of Series we can use the index label
data = np.array([2,4,6,8,10])
nilai_series = pd.Series(data, index=['a','b','c','d','e'])
print(nilai_series['a'])
print(nilai_series['d'])

2
8


## Access Data Series
In addition to being able to access Series value from the label, you can also access the index, such as NumPy. Index Series also starts from 0

In [ ]:
data = np.array([2,4,6,8,10])
nilai_series = pd.Series(data, index=['a','b','c','d','e'])
print(nilai_series[0])
print(nilai_series[3])

2
8


# To take series data use “:”

For example, if you want to take values starting from the 2nd index to the end,

In [4]:
data = np.array([2,4,6,8,10])
value_series = pd.Series(data, index=['a','b','c','d','e'])
print(value_series[2:])

c     6
d     8
e    10
dtype: int64


# loc and iloc
The loc is used to index data as in the above case

In [5]:
data = np.array([2,4,6,8,10])
value_series = pd.Series(data)
print(value_series.loc[0])
print(value_series.loc[2])

2
6


The iloc function is almost the same as loc, but only for index integers. So when the index label is not an integer then an error will occur when calling

For example if we create a Series with label index not integer

In [9]:
data = np.array([2,4,6,8,10])
value_series = pd.Series(data, index=['a','b','c','d','e'])
print(value_series.iloc['a'])
#When called the explicit label will be error

TypeError: ignored



---



---



Day-16 of #100DaysOfCode

# Practice
We will do Pandas Series handson with real dataset

The dataset that will be used is the Titanic dataset which is one of the well-known datasets

In [11]:
import numpy as np
import pandas as pd

In [12]:
#Next, use the read_csv() function to read the Titanic dataset 
#in the form of a CSV file and save it as a variable.

data = pd.read_csv('titanic.csv')

In [14]:
'''
The data will be stored in the data variable, 
then we will process it with Pandas Series and we focus on the column Name
'''
data_series = pd.Series(data['Name'])

In [15]:
#Use the head() function to return a sample of the top 5 data (default)
data_series.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [16]:
#We can also use tail() function to get the last 5 data
data_series.tail()

886                       Montvila, Rev. Juozas
887                Graham, Miss. Margaret Edith
888    Johnston, Miss. Catherine Helen "Carrie"
889                       Behr, Mr. Karl Howell
890                         Dooley, Mr. Patrick
Name: Name, dtype: object

In [17]:
'''
Next we will try slicing data
For example, displaying the name of the 100th and 200th index passengers
'''
print(data_series[100])
print(data_series[200])

Petranec, Miss. Matilda
Vande Walle, Mr. Nestor Cyriel


In [18]:
#We can also use loc() or iloc() functions
print(data_series.loc[100])
print(data_series.loc[200])

Petranec, Miss. Matilda
Vande Walle, Mr. Nestor Cyriel
